config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  resources :converts
  

   root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/converts_controller.rb
class ConvertsController < ApplicationController
  #require 'exchange'
  
  protect_from_forgery :except => :create
  before_filter :set_response_header
  
  def index
    render :layout => 'widget.js.erb', :content_type => 'application/javascript'
  end
  
  def show
    render :layout => 'widget.js.erb', :content_type => 'application/javascript'
  end
  
  def create
    require 'exchange'
    @amount = params[:amount].to_f
    @date = params[:date].split("-")
    @result = @amount.in(params[:from_currency].to_sym, at: Time.gm(@date[0],@date[1],@date[2]))
                  .to(params[:to_currency].to_sym).to_f
              
    render :layout => 'widget.js.erb', :content_type => 'application/javascript'
  end
  
  def set_response_header
      response.headers['Access-Control-Allow-Origin'] = '*'
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/convert_helper.rb
module ConvertHelper
end

app/helpers/currency_helper.rb
module CurrencyHelper

# Sort by full currency name
SORTED_CURRENCIES = Exchange::ISO.definitions.to_a.sort_by { |key, hash| hash[:currency] }

# Gather up all supported currencies across the main API (OpenExchangeRates)
# plus the fallback APIs (ECB and XavierMedia). These include some currencies
# not defined in the ISO definitions - those are rejected.
oer = Exchange::ExternalAPI::OpenExchangeRates::CURRENCIES

COMMON_CURRENCIES = %w(usd nzd aud gbp cad eur).map(&:to_sym)
SUPPORTED_CURRENCIES = oer.reject { |key| !Exchange::ISO.definitions.keys.include?(key) }
UNSUPPORTED_CURRENCIES = Exchange::ISO.definitions.keys - SUPPORTED_CURRENCIES

CURRENCIES       = {}
CURRENCY_OPTIONS = {}
CURRENCY_KEYS    = {
  :common      => COMMON_CURRENCIES,
  :supported   => SUPPORTED_CURRENCIES - COMMON_CURRENCIES
}

[ :common, :supported ].each do |group_sym|
  CURRENCIES[group_sym] = SORTED_CURRENCIES.select { |key, hash| CURRENCY_KEYS[group_sym].include?(key) }
  CURRENCY_OPTIONS[group_sym] = CURRENCIES[group_sym].map { |key, hash| ["#{hash[:currency]} - #{key.to_s.upcase}" << (hash[:symbol].present? ? " (#{hash[:symbol]})" : ''), key] }
end

CURRENCY_OPTIONS[:grouped] = [
  ["Common Currencies", CURRENCY_OPTIONS[:common]],
  ["Supported Currencies", CURRENCY_OPTIONS[:supported]]
]


def base_currency_code_select(curr)
  select_tag(curr, grouped_options_for_select(CurrencyHelper::CURRENCY_OPTIONS[:grouped]).html_safe, { :style => "width:160px" })
end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/converts/create.html.erb
<%= stylesheet_link_tag "//localhost:3000/assets/format.css" %>

<div>
  <table>
    <tr>
      <th rowspan="2" colspan="2"><h2>Currency converter</h2></th>
    </tr>
    <tr>
    </tr>
    <tr>
      <td style="text-align:center"><h2><%= params[:amount] %> <%= params[:fromCurr]%> converts to <%= sprintf('%.2f', @result) %> <%= params[:toCurr] %> </h2></td>
    </tr>
    <tr>
      <td><%= link_to 'New conversion', converts_url, :remote => true %></td>
    </tr>
    <tr>
      <td><button type="button" id="exit">X</button></td>
    </tr>
  </table>
</div>

app/views/converts/index.html.erb
<%= stylesheet_link_tag "//localhost:3000/assets/format.css" %>

<div>
<%= form_tag converts_url, :method=>'post', :remote => true do %>
   <table>
     <tr>
       <th rowspan="2" colspan="2"><h2>Currency converter</h2></th>
     </tr>
     <tr>
     <tr>
       <td>Amount: <%= number_field_tag 'amount' %></td>
     </tr>
     <tr>   
       <td>From Currency: <%=  base_currency_code_select("from_currency") %></td>
       <td>To Currency: <%=  base_currency_code_select("to_currency") %></td>
     </tr>  
     <tr>
       <td>Date: <%= date_field_tag 'date', Time.new.strftime('%Y-%m-%d') %></td>
     </tr>  
     <tr>
       <td><%= submit_tag "Convert" %></td>
      </tr>
      <tr>
        <td><button type="button" id="exit">X</button></td>
      </tr> 
    </table> 
<% end %>  
</div>

app/views/converts/show.html.erb
<%= stylesheet_link_tag "//localhost:3000/assets/format.css" %>

<div>
<%= form_tag converts_url, :method=>'post', :remote => true do %>
   <table>
     <tr>
       <th rowspan="2" colspan="2"><h2>Currency converter</h2></th>
     </tr>
     <tr>
     <tr>
       <td>Amount: <%= number_field_tag 'amount' %></td>
     </tr>
     <tr>   
       <td>From Currency: <%=  base_currency_code_select("from_currency") %></td>
       <td>To Currency: <%=  base_currency_code_select("to_currency") %></td>
     </tr>  
     <tr>
       <td>Date: <%= date_field_tag 'date', Time.new.strftime('%Y-%m-%d') %></td>
     </tr>  
     <tr>
       <td><%= submit_tag "Convert" %></td>
       </tr>
       <tr>
         <td><button type="button" id="exit">X</button></td>
       </tr> 
    </table> 
<% end %>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Converter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/widget.js.erb
 <% if params[:embed] %>
var clicked = false;
$(document).ready(function() {
  $('button').click(function() {
    console.log("this is for open it, what chu doin here unless you pressed open it, in that case youre fine");
    if (!clicked) {
    clicked = true;  
  Widget = (function() {

    var iFrame;
    var initialContent; 
    var iFrameDoc;

    function htmlLayout() {
      return '<%= escape_javascript(<<EOHTML.html_safe)
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="#{I18n.locale}" lang="#{I18n.locale}">

  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    #{stylesheet_link_tag "http://localhost:3000/assets/format.css", :cache => 'widget'}
    #{javascript_include_tag "http://localhost:3000/assets/widget_support.js", :cache => 'widget'}
    <script>
    $('#openit').click(function(event) {
      console.log("I have no idea what this is for now");
      event.preventDefault();
      parent.Widget.replaceContentWithScript($(this).attr('href'));
    });
    </script>
    <script>
    $('#exit').click(function(event) {
      console.log("Yey! exit button");
      event.preventDefault();
      parent.Widget.removeIFrame();
    });
    </script>
    </script>
  </head>

  <body id="top" class="partner_search" data-lang="#{I18n.locale}">
    <div id="iframe_content"></div>
  </body>
</html>
EOHTML
      %>';
    }

    function locateIFrameDoc() {
      var doc;
      if ( iFrame.contentDocument ) { 
        doc = iFrame.contentDocument; 
      } else if ( iFrame.contentWindow ) {
        doc = iFrame.contentWindow.document; 
      } else {
        doc = window.frames[iFrame.name].document;
      }
      return doc;
    }

    function createIFrame() {
      var canvas = document.getElementById('widget_canvas');
      iFrame = document.createElement('iframe');
      iFrame.name = iFrame.id = 'my_widget';
      iFrame.frameBorder = '0';
      iFrame.scrolling = 'no';
      iFrame.width = '380';
      iFrame.height = '240';
      canvas.style.width = '380px';
      canvas.style.height = '240px';
      canvas.appendChild(iFrame);
      iFrame.onload = insertInitialContent;
      iFrameDoc = locateIFrameDoc();
    }
    
    function removeIFrame() {
      var canvas = document.getElementById('widget_canvas');
      iFrame = document.removeElement('iframe');
    }

    function populateIFrame() {
      iFrameDoc.write(htmlLayout());
      iFrameDoc.close();
      initialContent = '<%= escape_javascript(yield) %>';
    }

    function replaceContent(content) {
      if ( iFrame.contentWindow.replaceIFrameContent ) {
        iFrame.contentWindow.replaceIFrameContent(content);
      }
      resizeIFrame();
    }

    function insertInitialContent() {
      if ( initialContent ) {
        replaceContent(initialContent);
        initialContent = null;
      }
    }

    function resizeIFrame() {
      iFrame.height = iFrameDoc.body.scrollHeight;
    }

    function replaceContentWithScript(scriptHref) {
      var scriptTag = document.createElement('script');
      scriptTag.type = 'text/javascript';
      scriptTag.src = scriptHref;
      document.body.appendChild(scriptTag);
    }

    function init() {
      createIFrame();
      populateIFrame();
    }

    init();

    return { replaceContent: replaceContent, replaceContentWithScript: replaceContentWithScript };
  })();
  }
  });
  });

<% else %>

  window.parent.Widget.replaceContent('<%= escape_javascript(yield) %>');

<% end %>

app/views/welcome/index.html.erb
<%= form_tag converts_url, :method=>'post', :remote => true do %>

<div>
  <table>
    <tr>
      <th rowspan="2"><h2>Currency converter</h2></th>
    </tr>
    <tr>
    </tr>
    <tr>
      <td><%= link_to 'New conversion', converts_url, :remote => true %></td>
    </tr>
    <tr>
      <td><button type="button" id="exit">X</button></td>
    </tr>
  </table>
</div>